version: "3.3"
services:
  app:
    container_name: "discord_youtube_share_bot-app"
    restart: always
    build: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_BOT_DEVELOPER_ID: ${DISCORD_BOT_DEVELOPER_ID}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    working_dir: "/app"
    command: python -O main.py
