version: "3.3"
services:
  app:
    container_name: "discord_youtube_share_bot-app"
    restart: always
    build: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    working_dir: "/app"
    command: python -O main.py
